# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76fc082cef8a2efaa8c4703c181f60389f2a6bddb07037f91dcd14d50cfb9820617d2107e332ddeda3d811c75fd0e9e1a107c7b7f0520fda449e703c150f2e7c

test:
  secret_key_base: 3737b803f23b2c2ccabd26da5bdcf4c3d8b46a3be7279caf1ab4b2e8226265d0cda79f13cf7f3c8dfb016bb4d494ae7116839c359b4e0dffe8ac5198822aecfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
